import type { Community, WeeklyDrop, Profile, Post, LeaderboardEntry, Group, DropProgress } from '@/types/database'

export const mockCommunities: Community[] = [
  { id: 'community-001', name: 'Alt AI Labs', slug: 'alt-ai-labs', description: 'Learn AI by building real products. Weekly drops, challenges, and cash prizes.', logo_url: null, accent_color: 'green', owner_id: 'admin', member_count: 127, created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'community-002', name: 'Vibe Coders', slug: 'vibe-coders', description: 'Ship apps with AI-assisted coding. Weekly vibe coding sessions with Cursor, Claude, and Copilot.', logo_url: null, accent_color: 'violet', owner_id: 'u2', member_count: 84, created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'community-003', name: 'AI for Teachers', slug: 'ai-for-teachers', description: 'Practical AI tools for educators. Build lesson planners, grading assistants, and feedback systems.', logo_url: null, accent_color: 'blue', owner_id: 'u3', member_count: 203, created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString() },
]

export const weeklyDrops: WeeklyDrop[] = [
  // Alt AI Labs — completed
  { id: 'drop-001', community_id: 'community-001', week_number: 1, title: 'Build Your First AI Assistant', slug: 'build-your-first-ai-assistant', description: 'Build a working AI assistant using Claude. API setup, tool use, and deployment to Vercel.', video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', thumbnail_url: null, duration_minutes: 28, difficulty: 'beginner', is_free: true, challenge_brief: `Build a working AI assistant that solves a real problem you face daily.\n\nIdeas:\n- Email draft assistant\n- Meeting notes summarizer\n- Daily task planner\n- Code review helper`, challenge_deliverables: ['Working demo or video walkthrough', 'GitHub repo or project link', 'Short writeup explaining your approach'], challenge_rules: ['Must be original work', 'Any AI API allowed', 'Submit before the deadline', 'One submission per person'], challenge_deadline: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), prize_description: 'Community recognition', prize_amount: 0, status: 'completed', submissions_count: 14, created_at: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(), updated_at: new Date().toISOString() },
  { id: 'drop-002', community_id: 'community-001', week_number: 2, title: 'AI Sales Agent That Actually Closes', slug: 'ai-sales-agent-that-actually-closes', description: 'Build an AI-powered outbound agent — lead scraping, personalized emails, and follow-up sequences.', video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', thumbnail_url: null, duration_minutes: 42, difficulty: 'intermediate', is_free: false, challenge_brief: `Build an AI system that automates one stage of the sales pipeline.\n\nPick one:\n- Lead qualification bot\n- Outreach personalization engine\n- Follow-up sequence automator`, challenge_deliverables: ['Live demo URL or video', 'Source code repository', 'Architecture writeup'], challenge_rules: ['Must be original work', 'Pro members only', 'Submit before deadline'], challenge_deadline: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), prize_description: '$500 cash prize', prize_amount: 500, status: 'completed', submissions_count: 8, created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(), updated_at: new Date().toISOString() },
  // Alt AI Labs — live
  { id: 'drop-003', community_id: 'community-001', week_number: 3, title: 'AI Executive Assistant in Claude Code + VS Code', slug: 'ai-executive-assistant-claude-code', description: 'Build a full AI executive assistant using Claude Code inside VS Code — email triage, calendar management, daily briefings, and task prioritization.', video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', thumbnail_url: null, duration_minutes: 45, difficulty: 'intermediate', is_free: false, challenge_brief: `Build an AI executive assistant that handles your daily operations:\n\n- Email triage: categorize (urgent / needs reply / FYI / spam) and draft responses\n- Calendar intelligence: surface scheduling conflicts, suggest meeting prep\n- Daily briefing: auto-generate a morning summary of tasks, emails, and priorities\n- Task extraction: pull action items from emails and Slack into a unified list\n\nUse Claude Code inside VS Code to build the entire thing live.`, challenge_deliverables: ['Working prototype with at least 2 features', 'Demo video showing real usage', 'Source code on GitHub'], challenge_rules: ['Must use Claude API or Claude Code', 'Any additional stack allowed', 'Submit before deadline'], challenge_deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(), prize_description: '$500 for the best executive assistant', prize_amount: 500, status: 'live', submissions_count: 3, created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), updated_at: new Date().toISOString() },
  // Alt AI Labs — upcoming (coming soon)
  { id: 'drop-004', community_id: 'community-001', week_number: 4, title: 'Solo OS — Your Personal AI Operating System', slug: 'solo-os-personal-ai-operating-system', description: 'Build "Solo OS" — a personal AI command center that manages your tasks, notes, calendar, and habits from a single dashboard powered by AI agents.', video_url: null, thumbnail_url: null, duration_minutes: 50, difficulty: 'advanced', is_free: false, challenge_brief: `Build your Solo OS — a personal operating system powered by AI:\n\n- Unified inbox: tasks, notes, calendar events in one feed\n- AI copilot: natural language commands ("reschedule my 3pm", "summarize today")\n- Habit tracker with AI coaching\n- Smart daily planner that auto-prioritizes based on deadlines and energy levels\n- Integrations: Google Calendar, Notion, Todoist, or any API\n\nThis is about building the system you wish existed for running your life.`, challenge_deliverables: ['Working app (web or CLI)', 'At least 3 integrated modules', 'Demo video', 'Source code'], challenge_rules: ['Any AI API allowed', 'Must be a usable product, not a demo', 'Submit before deadline'], challenge_deadline: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(), prize_description: '$750 grand prize for best Solo OS', prize_amount: 750, status: 'upcoming', submissions_count: 0, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'drop-005', community_id: 'community-001', week_number: 5, title: 'AI YouTube Autopilot — Script to Upload', slug: 'ai-youtube-autopilot-script-to-upload', description: 'Build an AI pipeline that generates video scripts, creates thumbnails, writes descriptions and tags — from a single topic input to YouTube-ready content.', video_url: null, thumbnail_url: null, duration_minutes: 40, difficulty: 'intermediate', is_free: false, challenge_brief: `Build an AI content pipeline for YouTube:\n\n- Topic → research → script generation (with hooks, structure, CTA)\n- Auto-generate thumbnail concepts with DALL-E or Midjourney prompts\n- SEO-optimized title, description, and tags\n- Content calendar: batch-plan 30 days of videos from one brainstorm\n\nBonus: integrate with YouTube Data API for direct publishing.`, challenge_deliverables: ['Working pipeline (web app or script)', 'Sample output for 3 different topics', 'Source code'], challenge_rules: ['Any AI API allowed', 'Must produce publishable output', 'Submit before deadline'], challenge_deadline: new Date(Date.now() + 19 * 24 * 60 * 60 * 1000).toISOString(), prize_description: '$500 for best content engine', prize_amount: 500, status: 'upcoming', submissions_count: 0, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'drop-006', community_id: 'community-001', week_number: 6, title: 'Voice AI Receptionist for Small Business', slug: 'voice-ai-receptionist-small-business', description: 'Build a voice AI agent that answers phone calls, books appointments, answers FAQs, and sends follow-up texts — using Twilio, ElevenLabs, and Claude.', video_url: null, thumbnail_url: null, duration_minutes: 45, difficulty: 'advanced', is_free: false, challenge_brief: `Build a voice AI receptionist:\n\n- Answer inbound calls with natural voice (ElevenLabs or similar)\n- Understand caller intent: book appointment, ask question, leave message\n- Integrate with Google Calendar for real-time availability\n- Send SMS confirmations after booking\n- Handle edge cases: "Let me transfer you", unknown requests\n\nStack: Twilio Voice + ElevenLabs + Claude + Google Calendar API`, challenge_deliverables: ['Working phone number that answers calls', 'Demo video of a full call flow', 'Architecture diagram', 'Source code'], challenge_rules: ['Must handle at least 3 call scenarios', 'Must use voice synthesis (not text-to-speech robot)', 'Submit before deadline'], challenge_deadline: new Date(Date.now() + 26 * 24 * 60 * 60 * 1000).toISOString(), prize_description: '$750 for best voice agent', prize_amount: 750, status: 'upcoming', submissions_count: 0, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'drop-007', community_id: 'community-001', week_number: 7, title: 'AI Code Review Agent for GitHub', slug: 'ai-code-review-agent-github', description: 'Build a GitHub bot that automatically reviews PRs — catches bugs, suggests improvements, checks for security issues, and comments inline like a senior engineer.', video_url: null, thumbnail_url: null, duration_minutes: 35, difficulty: 'intermediate', is_free: true, challenge_brief: `Build an AI code review bot for GitHub:\n\n- Auto-trigger on new PRs via GitHub webhooks\n- Analyze code changes for: bugs, performance, security, style\n- Leave inline comments on specific lines\n- Generate a summary review comment with severity levels\n- Learn from repo patterns (bonus)\n\nStack: GitHub API + Webhooks + Claude API + Vercel (or any hosting)`, challenge_deliverables: ['Working GitHub App or webhook integration', 'Demo on a real PR', 'Source code'], challenge_rules: ['Must work on real GitHub PRs', 'Any AI API allowed', 'Submit before deadline'], challenge_deadline: new Date(Date.now() + 33 * 24 * 60 * 60 * 1000).toISOString(), prize_description: '$250 for best code review bot', prize_amount: 250, status: 'upcoming', submissions_count: 0, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'drop-008', community_id: 'community-001', week_number: 8, title: 'Ship a SaaS MVP in One Weekend with AI', slug: 'saas-mvp-one-weekend-ai', description: 'The ultimate challenge: build and launch a complete SaaS product in 48 hours using AI-assisted coding. Auth, payments, dashboard, landing page — everything.', video_url: null, thumbnail_url: null, duration_minutes: 55, difficulty: 'advanced', is_free: false, challenge_brief: `Build a complete SaaS MVP in one weekend:\n\n- Landing page with waitlist or signup\n- User auth (Supabase, Clerk, or Auth.js)\n- Core feature that solves a real problem\n- Stripe payments (free trial + paid plan)\n- Dashboard with usage metrics\n- Deploy to production\n\nUse Claude Code, Cursor, Copilot — whatever makes you fastest.\nThe goal is SHIPPED, not perfect.`, challenge_deliverables: ['Live deployed URL', 'Working payments (test mode OK)', 'Time-lapse or build log', 'Source code'], challenge_rules: ['Must be built in 48 hours (honor system)', 'Must have auth + payments + core feature', 'Must be deployed and usable', 'Submit before deadline'], challenge_deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(), prize_description: '$1000 grand prize for best SaaS', prize_amount: 1000, status: 'upcoming', submissions_count: 0, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  // Vibe Coders
  { id: 'drop-vc-001', community_id: 'community-002', week_number: 1, title: 'Ship a Landing Page in 30 Minutes', slug: 'ship-a-landing-page-in-30-minutes', description: 'Use Cursor + Claude to build and deploy a landing page from a single prompt.', video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', thumbnail_url: null, duration_minutes: 32, difficulty: 'beginner', is_free: true, challenge_brief: `Vibe code a complete landing page for any product idea. Screen record your session.`, challenge_deliverables: ['Deployed URL', 'Screen recording', 'Total time spent'], challenge_rules: ['Must use AI-assisted coding', 'Under 60 minutes', 'Must be deployed'], challenge_deadline: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(), prize_description: '$200 for fastest ship', prize_amount: 200, status: 'live', submissions_count: 6, created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), updated_at: new Date().toISOString() },
  // AI for Teachers
  { id: 'drop-at-001', community_id: 'community-003', week_number: 1, title: 'Build an AI Lesson Planner', slug: 'build-an-ai-lesson-planner', description: 'Create a tool that generates week-long lesson plans from curriculum standards.', video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', thumbnail_url: null, duration_minutes: 25, difficulty: 'beginner', is_free: true, challenge_brief: `Build a lesson planner: input subject + grade → output structured weekly plan.`, challenge_deliverables: ['Working tool', 'Sample output for 3 subjects', 'Video demo'], challenge_rules: ['Must be usable by non-technical teachers', 'Any AI API allowed'], challenge_deadline: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(), prize_description: '$150 prize', prize_amount: 150, status: 'live', submissions_count: 11, created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), updated_at: new Date().toISOString() },
]

export function getCommunityBySlug(slug: string) { return mockCommunities.find(c => c.slug === slug) }
export function getDropsForCommunity(communityId: string) { return weeklyDrops.filter(d => d.community_id === communityId) }
export function getLeaderboardForCommunity(communityId: string) { return mockLeaderboard.filter(e => e.community_id === communityId) }
export function getPostsForCommunity(communityId: string) { return mockPosts.filter(p => p.community_id === communityId) }
export function getGroupsForCommunity(communityId: string) { return mockGroups.filter(g => g.community_id === communityId) }

export const mockProgress: DropProgress[] = [
  { id: 'p1', user_id: 'mock-user-id', drop_id: 'drop-001', watched: true, watched_at: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(), submitted: true, submitted_at: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'p2', user_id: 'mock-user-id', drop_id: 'drop-002', watched: true, watched_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), submitted: false, submitted_at: null },
]

export const mockProfile: Profile = { id: 'mock-user-id', email: 'builder@altailabs.com', full_name: 'Alex Builder', avatar_url: null, bio: 'Building AI systems every week.', membership_tier: 'free', stripe_customer_id: null, is_admin: false, total_points: 185, created_at: new Date().toISOString(), updated_at: new Date().toISOString() }

export const mockPosts: Post[] = [
  { id: '1', community_id: 'community-001', user_id: 'u1', title: 'Just shipped my first AI agent!', body: 'After the Week 1 lesson, I built an email triage agent. Saves me 2 hours a day.', category: 'wins', drop_id: 'drop-001', likes_count: 24, comments_count: 8, is_pinned: false, created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), updated_at: new Date().toISOString(), profile: { id: 'u1', email: 'maria@example.com', full_name: 'Maria Chen', avatar_url: null, bio: null, membership_tier: 'paid', stripe_customer_id: null, is_admin: false, total_points: 340, created_at: '', updated_at: '' } },
  { id: '2', community_id: 'community-001', user_id: 'u2', title: 'How do you handle rate limits with Claude?', body: 'Building a batch processing tool and keep hitting rate limits. What do you all use?', category: 'questions', drop_id: 'drop-003', likes_count: 12, comments_count: 15, is_pinned: false, created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(), updated_at: new Date().toISOString(), profile: { id: 'u2', email: 'james@example.com', full_name: 'James Wright', avatar_url: null, bio: null, membership_tier: 'free', stripe_customer_id: null, is_admin: false, total_points: 120, created_at: '', updated_at: '' } },
  { id: '3', community_id: 'community-001', user_id: 'u3', title: 'My sales agent just booked 3 demos', body: 'Used the Week 2 lesson to build an outreach engine. 3 demos in 24 hours.', category: 'builds', drop_id: 'drop-002', likes_count: 31, comments_count: 12, is_pinned: false, created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(), updated_at: new Date().toISOString(), profile: { id: 'u3', email: 'sam@example.com', full_name: 'Sam Torres', avatar_url: null, bio: null, membership_tier: 'paid', stripe_customer_id: null, is_admin: false, total_points: 280, created_at: '', updated_at: '' } },
  { id: '4', community_id: 'community-001', user_id: 'admin', title: 'Week 3 is LIVE — Inbox Triage', body: 'New drop just landed. $250 prize. Deadline is Friday.', category: 'announcements', drop_id: 'drop-003', likes_count: 45, comments_count: 6, is_pinned: true, created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(), updated_at: new Date().toISOString(), profile: { id: 'admin', email: 'admin@altailabs.com', full_name: 'Alt AI Labs', avatar_url: null, bio: null, membership_tier: 'paid', stripe_customer_id: null, is_admin: true, total_points: 0, created_at: '', updated_at: '' } },
]

export const mockLeaderboard: (LeaderboardEntry & { profile: Profile; rank: number })[] = [
  { id: '1', community_id: 'community-001', user_id: 'u3', points: 340, reason: '', created_at: '', rank: 1, profile: { id: 'u3', email: '', full_name: 'Maria Chen', avatar_url: null, bio: null, membership_tier: 'paid', stripe_customer_id: null, is_admin: false, total_points: 340, created_at: '', updated_at: '' } },
  { id: '2', community_id: 'community-001', user_id: 'u4', points: 295, reason: '', created_at: '', rank: 2, profile: { id: 'u4', email: '', full_name: 'Sam Torres', avatar_url: null, bio: null, membership_tier: 'paid', stripe_customer_id: null, is_admin: false, total_points: 295, created_at: '', updated_at: '' } },
  { id: '3', community_id: 'community-001', user_id: 'u5', points: 260, reason: '', created_at: '', rank: 3, profile: { id: 'u5', email: '', full_name: 'Priya Sharma', avatar_url: null, bio: null, membership_tier: 'paid', stripe_customer_id: null, is_admin: false, total_points: 260, created_at: '', updated_at: '' } },
  { id: '4', community_id: 'community-001', user_id: 'u6', points: 225, reason: '', created_at: '', rank: 4, profile: { id: 'u6', email: '', full_name: 'Jake Morrison', avatar_url: null, bio: null, membership_tier: 'free', stripe_customer_id: null, is_admin: false, total_points: 225, created_at: '', updated_at: '' } },
  { id: '5', community_id: 'community-001', user_id: 'u7', points: 185, reason: '', created_at: '', rank: 5, profile: { id: 'u7', email: '', full_name: 'Alex Builder', avatar_url: null, bio: null, membership_tier: 'free', stripe_customer_id: null, is_admin: false, total_points: 185, created_at: '', updated_at: '' } },
  { id: '6', community_id: 'community-001', user_id: 'u8', points: 170, reason: '', created_at: '', rank: 6, profile: { id: 'u8', email: '', full_name: 'Lin Wei', avatar_url: null, bio: null, membership_tier: 'paid', stripe_customer_id: null, is_admin: false, total_points: 170, created_at: '', updated_at: '' } },
  { id: '7', community_id: 'community-001', user_id: 'u9', points: 145, reason: '', created_at: '', rank: 7, profile: { id: 'u9', email: '', full_name: 'Omar Khalil', avatar_url: null, bio: null, membership_tier: 'free', stripe_customer_id: null, is_admin: false, total_points: 145, created_at: '', updated_at: '' } },
  { id: '8', community_id: 'community-001', user_id: 'u10', points: 130, reason: '', created_at: '', rank: 8, profile: { id: 'u10', email: '', full_name: 'Ava Johnson', avatar_url: null, bio: null, membership_tier: 'paid', stripe_customer_id: null, is_admin: false, total_points: 130, created_at: '', updated_at: '' } },
]

export const mockGroups: Group[] = [
  { id: 'g1', community_id: 'community-001', name: 'General Builders', slug: 'general-builders', description: 'The main community space. Share progress, ask questions, connect.', visibility: 'public', cover_image_url: null, max_members: null, created_at: new Date().toISOString(), _count: { group_members: 127 } },
  { id: 'g2', community_id: 'community-001', name: 'Pro Builders Circle', slug: 'pro-builders-circle', description: 'Exclusive group for Pro members. Deep dives, accountability, direct access.', visibility: 'private', cover_image_url: null, max_members: 50, created_at: new Date().toISOString(), _count: { group_members: 34 } },
  { id: 'g3', community_id: 'community-001', name: 'AI Sales Builders', slug: 'ai-sales-builders', description: 'Focused on building AI-powered sales tools.', visibility: 'public', cover_image_url: null, max_members: null, created_at: new Date().toISOString(), _count: { group_members: 56 } },
]
