import type { Community, WeeklyDrop, Profile, Post, LeaderboardEntry, Group, DropProgress } from '@/types/database'

export const mockCommunities: Community[] = [
  { id: 'community-001', name: 'Alt AI Labs', slug: 'alt-ai-labs', description: 'Learn AI by building real products. Weekly drops, challenges, and cash prizes.', logo_url: null, accent_color: 'green', owner_id: 'admin', member_count: 127, created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'community-002', name: 'Vibe Coders', slug: 'vibe-coders', description: 'Ship apps with AI-assisted coding. Weekly vibe coding sessions with Cursor, Claude, and Copilot.', logo_url: null, accent_color: 'violet', owner_id: 'u2', member_count: 84, created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'community-003', name: 'AI for Teachers', slug: 'ai-for-teachers', description: 'Practical AI tools for educators. Build lesson planners, grading assistants, and feedback systems.', logo_url: null, accent_color: 'blue', owner_id: 'u3', member_count: 203, created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString() },
]

export const weeklyDrops: WeeklyDrop[] = [
  // Alt AI Labs — LIVE — Sponsored by AITIM HOLDING
  { id: 'drop-001', community_id: 'community-001', week_number: 1, title: '5 AI Workflows That Actually Sell in 2026', slug: '5-ai-workflows-that-sell', description: 'I built 500 AI workflows, and these are the 5 that actually sell in 2026. Learn the "boring" automations businesses actually pay for — and build one yourself.', video_url: 'https://www.youtube.com/embed/Y3PcRp5RFzk', thumbnail_url: null, duration_minutes: 14, difficulty: 'beginner', is_free: true, challenge_brief: `Watch the video and build an AI Sales Agent using VSCode + Claude.\n\nIn this video, I break down 5 "boring" AI workflows that businesses actually want in 2026, based on building 500 AI workflows myself. If you're trying to figure out what businesses really want (not just what sounds cool), this is what's working right now.\n\nThese are simple, high-demand AI workflows you can build, sell, and scale in 2026.\n\nTIMESTAMPS\n00:42 - Easiest Automation to Sell\n02:54 - The "Boring" Money Maker\n05:12 - Why Leads Don't Convert\n07:40 - Hidden Money in Your CRM\n09:37 - The Stickiest Automation to Sale\n11:00 - The Most Profitable Automation I've seen\n11:50 - How to Sell Them?\n\nYour challenge: Pick ONE of the 5 workflows and build a working prototype using Claude + VSCode.`, challenge_deliverables: ['Working AI workflow prototype', 'Demo video or live URL', 'GitHub repo with source code', 'Short writeup: which workflow you chose and why'], challenge_rules: ['Must use Claude API or Claude Code', 'Build one of the 5 workflows from the video', 'Submit before the deadline', 'One submission per person'], challenge_deadline: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(), prize_description: 'Sponsored by AITIM HOLDING', prize_amount: 500, prize_per_entrant: 0, min_entrants_for_prize: 0, sponsor_name: 'AITIM HOLDING', sponsor_logo_url: null, sponsor_url: 'https://aitim.holding', status: 'live', submissions_count: 7, created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), updated_at: new Date().toISOString() },

  // Alt AI Labs — LIVE — Sponsored by AITIM HOLDING
  { id: 'drop-002', community_id: 'community-001', week_number: 2, title: 'AI for Content Creation', slug: 'ai-for-content-creation', description: 'Learn how to use AI to create, repurpose, and scale content across platforms. Build your own AI content pipeline.', video_url: 'https://www.youtube.com/embed/tW40b122Rbs', thumbnail_url: null, duration_minutes: 20, difficulty: 'intermediate', is_free: true, challenge_brief: `Watch the video and build an AI-powered content creation system.\n\nYour challenge: Build a tool that takes a single piece of content (blog post, video script, or idea) and automatically repurposes it into multiple formats — social posts, email newsletters, video scripts, and more.\n\nUse Claude API, Claude Code, or any AI tool to build it.`, challenge_deliverables: ['Working content repurposing tool', 'Demo showing input → multiple outputs', 'GitHub repo with source code', 'Writeup explaining your approach'], challenge_rules: ['Must produce at least 3 different content formats from one input', 'Any AI API allowed', 'Submit before the deadline', 'One submission per person'], challenge_deadline: new Date(Date.now() + 13 * 24 * 60 * 60 * 1000).toISOString(), prize_description: 'Sponsored by AITIM HOLDING', prize_amount: 500, prize_per_entrant: 0, min_entrants_for_prize: 0, sponsor_name: 'AITIM HOLDING', sponsor_logo_url: null, sponsor_url: 'https://aitim.holding', status: 'live', submissions_count: 3, created_at: new Date(Date.now() - 0 * 24 * 60 * 60 * 1000).toISOString(), updated_at: new Date().toISOString() },

  // Alt AI Labs — Upcoming — Sponsored by AITIM HOLDING
  { id: 'drop-003', community_id: 'community-001', week_number: 3, title: 'Build a Website with AI', slug: 'build-a-website-with-ai', description: 'Use AI tools to design and build a complete, production-ready website from scratch. No templates — just you, AI, and a blank canvas.', video_url: 'https://www.youtube.com/embed/86HM0RUWhCk', thumbnail_url: null, duration_minutes: 25, difficulty: 'beginner', is_free: true, challenge_brief: `Watch the video and build a complete website using AI.\n\nYour challenge: Build a professional, production-ready website for any business or project idea. Use AI to generate the design, write the copy, and ship it live.\n\nBonus points for:\n- Responsive design (mobile + desktop)\n- Real content (not lorem ipsum)\n- Deployed to a live URL\n- Creative use of AI in the build process`, challenge_deliverables: ['Live deployed website URL', 'Screen recording of your build process', 'GitHub repo with source code', 'Brief writeup on how AI helped'], challenge_rules: ['Must use AI tools in the build process', 'Website must be deployed and accessible', 'Submit before the deadline', 'One submission per person'], challenge_deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(), prize_description: 'Sponsored by AITIM HOLDING', prize_amount: 500, prize_per_entrant: 0, min_entrants_for_prize: 0, sponsor_name: 'AITIM HOLDING', sponsor_logo_url: null, sponsor_url: 'https://aitim.holding', status: 'upcoming', submissions_count: 0, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },

  // Alt AI Labs — upcoming
  { id: 'drop-004', community_id: 'community-001', week_number: 4, title: 'AI Executive Assistant in Claude Code', slug: 'ai-executive-assistant-claude-code', description: 'Build a full AI executive assistant using Claude Code inside VS Code — email triage, calendar management, daily briefings, and task prioritization.', video_url: null, thumbnail_url: null, duration_minutes: 45, difficulty: 'intermediate', is_free: false, challenge_brief: `Build an AI executive assistant that handles your daily operations:\n\n- Email triage: categorize (urgent / needs reply / FYI / spam) and draft responses\n- Calendar intelligence: surface scheduling conflicts, suggest meeting prep\n- Daily briefing: auto-generate a morning summary of tasks, emails, and priorities\n- Task extraction: pull action items from emails and Slack into a unified list\n\nUse Claude Code inside VS Code to build the entire thing live.`, challenge_deliverables: ['Working prototype with at least 2 features', 'Demo video showing real usage', 'Source code on GitHub'], challenge_rules: ['Must use Claude API or Claude Code', 'Any additional stack allowed', 'Submit before deadline'], challenge_deadline: new Date(Date.now() + 27 * 24 * 60 * 60 * 1000).toISOString(), prize_description: 'Pool grows with every Pro builder who enters', prize_amount: 0, prize_per_entrant: 50, min_entrants_for_prize: 5, sponsor_name: null, sponsor_logo_url: null, sponsor_url: null, status: 'upcoming', submissions_count: 0, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'drop-005', community_id: 'community-001', week_number: 5, title: 'Solo OS — Your Personal AI Operating System', slug: 'solo-os-personal-ai-operating-system', description: 'Build "Solo OS" — a personal AI command center that manages your tasks, notes, calendar, and habits from a single dashboard powered by AI agents.', video_url: null, thumbnail_url: null, duration_minutes: 50, difficulty: 'advanced', is_free: false, challenge_brief: `Build your Solo OS — a personal operating system powered by AI:\n\n- Unified inbox: tasks, notes, calendar events in one feed\n- AI copilot: natural language commands ("reschedule my 3pm", "summarize today")\n- Habit tracker with AI coaching\n- Smart daily planner that auto-prioritizes based on deadlines and energy levels\n- Integrations: Google Calendar, Notion, Todoist, or any API`, challenge_deliverables: ['Working app (web or CLI)', 'At least 3 integrated modules', 'Demo video', 'Source code'], challenge_rules: ['Any AI API allowed', 'Must be a usable product, not a demo', 'Submit before deadline'], challenge_deadline: new Date(Date.now() + 34 * 24 * 60 * 60 * 1000).toISOString(), prize_description: 'Pool grows with every Pro builder who enters', prize_amount: 0, prize_per_entrant: 75, min_entrants_for_prize: 5, sponsor_name: null, sponsor_logo_url: null, sponsor_url: null, status: 'upcoming', submissions_count: 0, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'drop-006', community_id: 'community-001', week_number: 6, title: 'AI YouTube Autopilot — Script to Upload', slug: 'ai-youtube-autopilot-script-to-upload', description: 'Build an AI pipeline that generates video scripts, creates thumbnails, writes descriptions and tags — from a single topic input to YouTube-ready content.', video_url: null, thumbnail_url: null, duration_minutes: 40, difficulty: 'intermediate', is_free: false, challenge_brief: `Build an AI content pipeline for YouTube:\n\n- Topic → research → script generation (with hooks, structure, CTA)\n- Auto-generate thumbnail concepts with DALL-E or Midjourney prompts\n- SEO-optimized title, description, and tags\n- Content calendar: batch-plan 30 days of videos from one brainstorm`, challenge_deliverables: ['Working pipeline (web app or script)', 'Sample output for 3 different topics', 'Source code'], challenge_rules: ['Any AI API allowed', 'Must produce publishable output', 'Submit before deadline'], challenge_deadline: new Date(Date.now() + 41 * 24 * 60 * 60 * 1000).toISOString(), prize_description: 'Pool grows with every Pro builder who enters', prize_amount: 0, prize_per_entrant: 50, min_entrants_for_prize: 5, sponsor_name: null, sponsor_logo_url: null, sponsor_url: null, status: 'upcoming', submissions_count: 0, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'drop-007', community_id: 'community-001', week_number: 7, title: 'Voice AI Receptionist for Small Business', slug: 'voice-ai-receptionist-small-business', description: 'Build a voice AI agent that answers phone calls, books appointments, answers FAQs, and sends follow-up texts.', video_url: null, thumbnail_url: null, duration_minutes: 45, difficulty: 'advanced', is_free: false, challenge_brief: `Build a voice AI receptionist:\n\n- Answer inbound calls with natural voice (ElevenLabs or similar)\n- Understand caller intent: book appointment, ask question, leave message\n- Integrate with Google Calendar for real-time availability\n- Send SMS confirmations after booking`, challenge_deliverables: ['Working phone number that answers calls', 'Demo video of a full call flow', 'Architecture diagram', 'Source code'], challenge_rules: ['Must handle at least 3 call scenarios', 'Must use voice synthesis', 'Submit before deadline'], challenge_deadline: new Date(Date.now() + 48 * 24 * 60 * 60 * 1000).toISOString(), prize_description: 'Pool grows with every Pro builder who enters', prize_amount: 0, prize_per_entrant: 75, min_entrants_for_prize: 5, sponsor_name: null, sponsor_logo_url: null, sponsor_url: null, status: 'upcoming', submissions_count: 0, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'drop-008', community_id: 'community-001', week_number: 8, title: 'Ship a SaaS MVP in One Weekend with AI', slug: 'saas-mvp-one-weekend-ai', description: 'The ultimate challenge: build and launch a complete SaaS product in 48 hours using AI-assisted coding.', video_url: null, thumbnail_url: null, duration_minutes: 55, difficulty: 'advanced', is_free: false, challenge_brief: `Build a complete SaaS MVP in one weekend:\n\n- Landing page with waitlist or signup\n- User auth (Supabase, Clerk, or Auth.js)\n- Core feature that solves a real problem\n- Stripe payments (free trial + paid plan)\n- Dashboard with usage metrics\n- Deploy to production`, challenge_deliverables: ['Live deployed URL', 'Working payments (test mode OK)', 'Time-lapse or build log', 'Source code'], challenge_rules: ['Must be built in 48 hours (honor system)', 'Must have auth + payments + core feature', 'Must be deployed and usable', 'Submit before deadline'], challenge_deadline: new Date(Date.now() + 55 * 24 * 60 * 60 * 1000).toISOString(), prize_description: 'Pool grows with every Pro builder who enters', prize_amount: 0, prize_per_entrant: 100, min_entrants_for_prize: 5, sponsor_name: null, sponsor_logo_url: null, sponsor_url: null, status: 'upcoming', submissions_count: 0, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  // Alt AI Labs — upcoming — Sponsored by AITIM HOLDING
  { id: 'drop-009', community_id: 'community-001', week_number: 9, title: 'Zero-Code $10M AI Business Blueprint', slug: 'zero-code-10m-ai-business', description: 'Watch Dan Martell break down how to build a $10M solo AI business with zero code — then prove it by launching your own AI micro-business in 7 days.', video_url: 'https://www.youtube.com/embed/w-XPlC3a2oI', thumbnail_url: null, duration_minutes: 18, difficulty: 'intermediate', is_free: true, challenge_brief: `Dan Martell just dropped the playbook for building a $10M solo AI business without writing a single line of code.\n\nYour challenge: Launch a real AI micro-business in 7 days.\n\nHere's the deal — pick a niche, build an AI-powered service using NO-CODE tools (Make, Zapier, n8n, Voiceflow, Claude, etc.), get it in front of real customers, and document the journey.\n\nWhat counts:\n- A real service that solves a real problem (not a demo)\n- At least 1 paying customer OR 10 waitlist signups\n- Built entirely with no-code/low-code + AI tools\n- A "business card" landing page that explains what you sell\n\nBonus points:\n- Revenue generated (even $1 counts!)\n- Customer testimonials or screenshots of conversations\n- A breakdown of your entire stack + costs\n- A video pitch like you're on Shark Tank (60 sec max)\n\nThis isn't a coding challenge. This is a BUSINESS challenge. Ship something people pay for.`, challenge_deliverables: ['Live landing page for your AI business', 'Proof of customer traction (screenshots, testimonials, or revenue)', 'Full stack breakdown (tools used + monthly cost)', '60-second video pitch of your business', 'GitHub or Notion doc with your build process'], challenge_rules: ['Must use AI as a core part of the product/service', 'No custom code — no-code/low-code tools only', 'Must have a live URL customers can visit', 'Must show proof of at least 1 customer interaction', 'Submit before the deadline'], challenge_deadline: new Date(Date.now() + 62 * 24 * 60 * 60 * 1000).toISOString(), prize_description: 'Sponsored by AITIM HOLDING', prize_amount: 500, prize_per_entrant: 0, min_entrants_for_prize: 0, sponsor_name: 'AITIM HOLDING', sponsor_logo_url: null, sponsor_url: 'https://aitim.holding', status: 'upcoming', submissions_count: 0, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'drop-010', community_id: 'community-001', week_number: 10, title: 'The AI Skills Gauntlet — Master All 9', slug: 'ai-skills-gauntlet-master-all-9', description: 'Dan Martell says there are 9 AI skills that put you ahead of 99% of people. Prove you have them — build a project that showcases at least 5 in one shot.', video_url: 'https://www.youtube.com/embed/BuwPnrMmhzQ', thumbnail_url: null, duration_minutes: 15, difficulty: 'advanced', is_free: true, challenge_brief: `Dan Martell just listed the 9 AI skills that separate the top 1% from everyone else.\n\nYour challenge: Build ONE project that demonstrates at least 5 of the 9 AI skills.\n\nThe 9 skills to target:\n1. Prompt Engineering — write prompts that get perfect outputs first try\n2. AI Workflow Design — chain multiple AI steps into automated pipelines\n3. Data Curation — feed AI the right context for better results\n4. AI-Augmented Decision Making — use AI to make faster, smarter choices\n5. Human-AI Collaboration — know when to use AI vs. do it yourself\n6. AI Tool Selection — pick the right AI tool for each job\n7. Output Validation — verify and improve AI-generated results\n8. AI Ethics & Safety — build responsibly (no hallucination disasters)\n9. Teaching AI to Others — document and share what you've learned\n\nBuild a project that clearly demonstrates 5+ of these skills. The most creative combo wins.\n\nExamples that would crush it:\n- An AI research assistant that curates data (3), chains workflows (2), validates outputs (7), and includes a "how I built this" guide (9)\n- A business dashboard that uses AI for decision support (4), picks between multiple AI models (6), has human review steps (5), and includes prompt templates (1)\n- A content pipeline with engineered prompts (1), automated workflows (2), quality checks (7), ethical guardrails (8), and a tutorial for your team (9)\n\nGet creative. The wilder the combo, the more points you score.`, challenge_deliverables: ['Working project (deployed URL or demo video)', 'Scorecard: which 5+ skills your project demonstrates and how', 'Architecture diagram showing the AI workflow', 'Source code or no-code stack breakdown', '"Teach it" component — a guide, video, or doc that teaches someone else one of the skills'], challenge_rules: ['Must demonstrate at least 5 of the 9 AI skills', 'Must include a self-assessment scorecard explaining which skills and how', 'Any tech stack allowed (code, no-code, or hybrid)', 'Must include the "teach" component (skill #9)', 'Submit before the deadline'], challenge_deadline: new Date(Date.now() + 69 * 24 * 60 * 60 * 1000).toISOString(), prize_description: 'Sponsored by AITIM HOLDING', prize_amount: 500, prize_per_entrant: 0, min_entrants_for_prize: 0, sponsor_name: 'AITIM HOLDING', sponsor_logo_url: null, sponsor_url: 'https://aitim.holding', status: 'upcoming', submissions_count: 0, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  // Vibe Coders
  { id: 'drop-vc-001', community_id: 'community-002', week_number: 1, title: 'Ship a Landing Page in 30 Minutes', slug: 'ship-a-landing-page-in-30-minutes', description: 'Use Cursor + Claude to build and deploy a landing page from a single prompt.', video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', thumbnail_url: null, duration_minutes: 32, difficulty: 'beginner', is_free: true, challenge_brief: `Vibe code a complete landing page for any product idea. Screen record your session.`, challenge_deliverables: ['Deployed URL', 'Screen recording', 'Total time spent'], challenge_rules: ['Must use AI-assisted coding', 'Under 60 minutes', 'Must be deployed'], challenge_deadline: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(), prize_description: 'Pool grows with every builder who enters', prize_amount: 0, prize_per_entrant: 25, min_entrants_for_prize: 5, sponsor_name: null, sponsor_logo_url: null, sponsor_url: null, status: 'live', submissions_count: 6, created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), updated_at: new Date().toISOString() },
  // AI for Teachers
  { id: 'drop-at-001', community_id: 'community-003', week_number: 1, title: 'Build an AI Lesson Planner', slug: 'build-an-ai-lesson-planner', description: 'Create a tool that generates week-long lesson plans from curriculum standards.', video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', thumbnail_url: null, duration_minutes: 25, difficulty: 'beginner', is_free: true, challenge_brief: `Build a lesson planner: input subject + grade → output structured weekly plan.`, challenge_deliverables: ['Working tool', 'Sample output for 3 subjects', 'Video demo'], challenge_rules: ['Must be usable by non-technical teachers', 'Any AI API allowed'], challenge_deadline: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(), prize_description: 'Pool grows with every builder who enters', prize_amount: 0, prize_per_entrant: 15, min_entrants_for_prize: 5, sponsor_name: null, sponsor_logo_url: null, sponsor_url: null, status: 'live', submissions_count: 11, created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), updated_at: new Date().toISOString() },
]

export function getCommunityBySlug(slug: string) { return mockCommunities.find(c => c.slug === slug) }
export function getDropsForCommunity(communityId: string) { return weeklyDrops.filter(d => d.community_id === communityId) }
export function getLeaderboardForCommunity(communityId: string) { return mockLeaderboard.filter(e => e.community_id === communityId) }
export function getPostsForCommunity(communityId: string) { return mockPosts.filter(p => p.community_id === communityId) }
export function getGroupsForCommunity(communityId: string) { return mockGroups.filter(g => g.community_id === communityId) }

export const mockProgress: DropProgress[] = [
  { id: 'p1', user_id: 'mock-user-id', drop_id: 'drop-001', watched: true, watched_at: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(), submitted: true, submitted_at: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'p2', user_id: 'mock-user-id', drop_id: 'drop-002', watched: true, watched_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), submitted: false, submitted_at: null },
]

export const mockProfile: Profile = { id: 'mock-user-id', email: 'builder@altailabs.com', full_name: 'Alex Builder', avatar_url: null, bio: 'Building AI systems every week.', membership_tier: 'free', stripe_customer_id: null, is_admin: false, total_points: 185, created_at: new Date().toISOString(), updated_at: new Date().toISOString() }

export const mockPosts: Post[] = [
  { id: '1', community_id: 'community-001', user_id: 'admin', title: 'Solo OS is live — my personal AI operating system', body: 'Just shipped Solo OS. It unifies my tasks, notes, calendar, and habits into one AI-powered command center. Natural language control — "reschedule my 3pm" just works. Built with Claude + Next.js + Vercel. This is what I use every day now.', category: 'wins', drop_id: 'drop-001', likes_count: 67, comments_count: 23, is_pinned: true, created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), updated_at: new Date().toISOString(), profile: { id: 'admin', email: 'admin@altailabs.com', full_name: 'Timur M.', avatar_url: null, bio: null, membership_tier: 'paid', stripe_customer_id: null, is_admin: true, total_points: 890, created_at: '', updated_at: '' } },
  { id: '2', community_id: 'community-001', user_id: 'admin', title: 'AI Site Builder — 12 client sites in the first month', body: 'Built a tool that generates production-ready websites from a single prompt. Responsive design, real copy, SEO optimization, one-click deploy. Already used it to ship 12 sites for real clients. The "boring" AI workflows that actually make money.', category: 'builds', drop_id: 'drop-001', likes_count: 45, comments_count: 18, is_pinned: false, created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(), updated_at: new Date().toISOString(), profile: { id: 'admin', email: 'admin@altailabs.com', full_name: 'Timur M.', avatar_url: null, bio: null, membership_tier: 'paid', stripe_customer_id: null, is_admin: true, total_points: 890, created_at: '', updated_at: '' } },
  { id: '3', community_id: 'community-001', user_id: 'admin', title: 'AI Song Creator — 3 artists on Spotify using my tracks', body: 'Turned a text prompt into full songs — lyrics, melody, arrangement, production. Used Claude for lyrics + Suno API for music generation. 3 independent artists are now using tracks I generated on Spotify. Wild.', category: 'wins', drop_id: 'drop-002', likes_count: 52, comments_count: 31, is_pinned: false, created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(), updated_at: new Date().toISOString(), profile: { id: 'admin', email: 'admin@altailabs.com', full_name: 'Timur M.', avatar_url: null, bio: null, membership_tier: 'paid', stripe_customer_id: null, is_admin: true, total_points: 890, created_at: '', updated_at: '' } },
  { id: '4', community_id: 'community-001', user_id: 'admin', title: 'AI YouTube Pipeline — 30 days of content from 1 brainstorm', body: 'Built an end-to-end YouTube content pipeline: topic research → script generation with hooks and CTAs → thumbnail concepts → SEO titles and descriptions. One brainstorm session gives me 30 days of planned content. Game changer for creators.', category: 'builds', drop_id: 'drop-002', likes_count: 38, comments_count: 14, is_pinned: false, created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(), updated_at: new Date().toISOString(), profile: { id: 'admin', email: 'admin@altailabs.com', full_name: 'Timur M.', avatar_url: null, bio: null, membership_tier: 'paid', stripe_customer_id: null, is_admin: true, total_points: 890, created_at: '', updated_at: '' } },
  { id: '5', community_id: 'community-001', user_id: 'u1', title: 'My sales agent just booked 3 demos in 24 hours', body: 'Used the AI Sales Workflows challenge to build an outreach engine with Claude. Personalized emails, follow-up sequences, lead scoring. 3 demos booked in the first day. This platform is insane.', category: 'wins', drop_id: 'drop-001', likes_count: 31, comments_count: 12, is_pinned: false, created_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(), updated_at: new Date().toISOString(), profile: { id: 'u1', email: 'maria@example.com', full_name: 'Maria Chen', avatar_url: null, bio: null, membership_tier: 'paid', stripe_customer_id: null, is_admin: false, total_points: 340, created_at: '', updated_at: '' } },
  { id: '6', community_id: 'community-001', user_id: 'u2', title: 'New challenge is LIVE — $500 prize by AITIM HOLDING', body: 'This week: 5 AI Workflows That Actually Sell. Watch the video, pick a workflow, build it. $500 prize sponsored by AITIM HOLDING. Let\'s go.', category: 'announcements', drop_id: 'drop-001', likes_count: 56, comments_count: 8, is_pinned: false, created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(), updated_at: new Date().toISOString(), profile: { id: 'admin', email: 'admin@altailabs.com', full_name: 'Alt AI Labs', avatar_url: null, bio: null, membership_tier: 'paid', stripe_customer_id: null, is_admin: true, total_points: 0, created_at: '', updated_at: '' } },
]

export const mockLeaderboard: (LeaderboardEntry & { profile: Profile; rank: number })[] = [
  { id: '1', community_id: 'community-001', user_id: 'u3', points: 340, reason: '', created_at: '', rank: 1, profile: { id: 'u3', email: '', full_name: 'Maria Chen', avatar_url: null, bio: null, membership_tier: 'paid', stripe_customer_id: null, is_admin: false, total_points: 340, created_at: '', updated_at: '' } },
  { id: '2', community_id: 'community-001', user_id: 'u4', points: 295, reason: '', created_at: '', rank: 2, profile: { id: 'u4', email: '', full_name: 'Sam Torres', avatar_url: null, bio: null, membership_tier: 'paid', stripe_customer_id: null, is_admin: false, total_points: 295, created_at: '', updated_at: '' } },
  { id: '3', community_id: 'community-001', user_id: 'u5', points: 260, reason: '', created_at: '', rank: 3, profile: { id: 'u5', email: '', full_name: 'Priya Sharma', avatar_url: null, bio: null, membership_tier: 'paid', stripe_customer_id: null, is_admin: false, total_points: 260, created_at: '', updated_at: '' } },
  { id: '4', community_id: 'community-001', user_id: 'u6', points: 225, reason: '', created_at: '', rank: 4, profile: { id: 'u6', email: '', full_name: 'Jake Morrison', avatar_url: null, bio: null, membership_tier: 'free', stripe_customer_id: null, is_admin: false, total_points: 225, created_at: '', updated_at: '' } },
  { id: '5', community_id: 'community-001', user_id: 'u7', points: 185, reason: '', created_at: '', rank: 5, profile: { id: 'u7', email: '', full_name: 'Alex Builder', avatar_url: null, bio: null, membership_tier: 'free', stripe_customer_id: null, is_admin: false, total_points: 185, created_at: '', updated_at: '' } },
  { id: '6', community_id: 'community-001', user_id: 'u8', points: 170, reason: '', created_at: '', rank: 6, profile: { id: 'u8', email: '', full_name: 'Lin Wei', avatar_url: null, bio: null, membership_tier: 'paid', stripe_customer_id: null, is_admin: false, total_points: 170, created_at: '', updated_at: '' } },
  { id: '7', community_id: 'community-001', user_id: 'u9', points: 145, reason: '', created_at: '', rank: 7, profile: { id: 'u9', email: '', full_name: 'Omar Khalil', avatar_url: null, bio: null, membership_tier: 'free', stripe_customer_id: null, is_admin: false, total_points: 145, created_at: '', updated_at: '' } },
  { id: '8', community_id: 'community-001', user_id: 'u10', points: 130, reason: '', created_at: '', rank: 8, profile: { id: 'u10', email: '', full_name: 'Ava Johnson', avatar_url: null, bio: null, membership_tier: 'paid', stripe_customer_id: null, is_admin: false, total_points: 130, created_at: '', updated_at: '' } },
]

export const mockGroups: Group[] = [
  { id: 'g1', community_id: 'community-001', name: 'General Builders', slug: 'general-builders', description: 'The main community space. Share progress, ask questions, connect.', visibility: 'public', cover_image_url: null, max_members: null, created_at: new Date().toISOString(), _count: { group_members: 127 } },
  { id: 'g2', community_id: 'community-001', name: 'Pro Builders Circle', slug: 'pro-builders-circle', description: 'Exclusive group for Pro members. Deep dives, accountability, direct access.', visibility: 'private', cover_image_url: null, max_members: 50, created_at: new Date().toISOString(), _count: { group_members: 34 } },
  { id: 'g3', community_id: 'community-001', name: 'AI Sales Builders', slug: 'ai-sales-builders', description: 'Focused on building AI-powered sales tools.', visibility: 'public', cover_image_url: null, max_members: null, created_at: new Date().toISOString(), _count: { group_members: 56 } },
]
